[metadata]
name = audiotree
version = attr: audiotree.__version__
url = https://github.com/DBraun/audiotree
author = David Braun
author_email = braun@ccrma.stanford.edu
description = Audio data loading and augmentations in JAX
long_description = file: README.md
long_description_content_type = "text/markdown"
classifiers =
    Intended Audience :: Developers
    Natural Language :: English
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Topic :: Multimedia :: Sound/Audio
    Topic :: Software Development :: Libraries

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    einops
    grain>=0.2.3
    jax-ai-stack>=2025.2.5
;    jaxloudnorm @ git+https://github.com/boris-kuz/jaxloudnorm.git
    librosa>=0.10.1
    numpy
    soundfile
    typing_extensions

[options.packages.find]
where = src

[options.extras_require]
dev =
    pytest
    pytest-cov
